kind: pipeline
type: docker
name: build

trigger:
  event:
    - tag

steps:
  - name: push-docker-image
    image: plugins/docker
    # image: node:14.15.0-alpine

    settings:
      repo: ${DRONE_REPO}
      registry: docker.pkg.github.com
      dockerfile: ./docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

    # commands:
    #   - docker ps
    # - docker build -t docker.pkg.github.com/${DRONE_REPO}/${DRONE_REPO_NAME}-image:${DRONE_TAG} ./docker
