kind: pipeline
type: docker
name: build

trigger:
  event:
    - tag

steps:
  - name: greeting
    image: node:14.15.0-alpine
    commands:
      - docker build -t docker.pkg.github.com/${DRONE_REPO}/${DRONE_REPO_NAME}-image:${DRONE_TAG} .
