kind: pipeline
type: docker
name: build

trigger:
  event:
    - tag

steps:
  - name: push-docker-image
    image: plugins/docker
    # image: node:14.15.0-alpine

    environment:
      CR_PAT:
        from_secret: CR_PAT

    settings:
      repo: ${DRONE_REPO}
      registry: ghcr.io/${DRONE_REPO_OWNER}
      dockerfile: ./docker/Dockerfile
      # username:
      #   from_secret: github_username
      # password:
      #   from_secret: github_password

    commands:
      # - echo $CR_PAT
      - echo $CR_PAT | docker login ghcr.io -u ${DRONE_REPO_NAME} --password-stdin
      - docker build -t ghcr.io/${DRONE_REPO}/${DRONE_REPO_NAME}-image:${DRONE_TAG} ./docker
