version: "3"
services:
  forum-mysql:
    container_name: forum-mysql
    image: mysql:5
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "forum"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  forum-server:
    container_name: forum-server
    build:
      context: ../
      dockerfile: "docker/Dockerfile"
    ports:
      - "4000:4000"
    depends_on:
      - forum-mysql
